[package]
name = "pike-bindings"
version = "0.1.0"
authors = ["Martin Karlgren <martin@karlgren.me>"]
build = "build.rs"

[dependencies]
pike-macros = { path = "pike-macros" }
serde = "1.0.41"
lazy_static = "1.0"

[build-dependencies]
bindgen = "0.35"
encoding = "0.2"